<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pedidos.Application\Pedidos.Application.csproj" />
    <ProjectReference Include="..\Pedidos.Domain\Pedidos.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pedidos.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migracoes\Scripts\*.sql" />
  </ItemGroup>

</Project>
